# Generated by Django 5.1.7 on 2025-03-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='VHOST_name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rb_username',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
