# Generated by Django 5.1.7 on 2025-04-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_session_end_time_alter_session_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.DurationField(editable=False, null=True),
        ),
    ]
