# Generated by Django 5.1.7 on 2025-03-26 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_token_vhost_name_alter_user_rb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='analytics.token')),
            ],
        ),
        migrations.CreateModel(
            name='KPIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='analytics.client')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='analytics.token')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalKPIDaily',
            fields=[
                ('date', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('total_users', models.IntegerField(default=0)),
                ('daily_active_users', models.IntegerField(default=0)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_data', to='analytics.token')),
            ],
            options={
                'unique_together': {('token', 'date')},
            },
        ),
    ]
