# Generated by Django 5.1.7 on 2025-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_GameEventHourlyCount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEventHourlyCount',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('event_count', models.IntegerField()),
            ],
            options={
                'db_table': 'gameeventcount_hourly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BussinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartType', models.CharField(max_length=300)),
                ('itemType', models.CharField(max_length=300)),
                ('itemId', models.CharField(max_length=300)),
                ('amount', models.IntegerField()),
                ('game_event', models.IntegerField()),
                ('currency', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_event', models.IntegerField()),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('Info', 'Info'), ('Debug', 'Debug'), ('Warning', 'Warning'), ('Error', 'Error'), ('Critical', 'Critical')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProgeressionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_event', models.IntegerField()),
                ('progressionStatus', models.CharField(max_length=300)),
                ('progression01', models.CharField(max_length=300)),
                ('progression02', models.CharField(max_length=300)),
                ('progression03', models.CharField(max_length=300)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QualityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_event', models.IntegerField()),
                ('FPS', models.FloatField()),
                ('memoryUsage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_event', models.IntegerField()),
                ('flowType', models.CharField(max_length=300)),
                ('itemType', models.CharField(max_length=300)),
                ('itemId', models.CharField(max_length=300)),
                ('amount', models.IntegerField()),
                ('resourceCurrency', models.CharField(max_length=300)),
            ],
        ),
    ]
