# Generated by Django 5.1.7 on 2025-04-18 06:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_session_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.RemoveField(
            model_name='token',
            name='VHOST_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rb_password',
            field=models.CharField(default='user', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='rb_username',
            field=models.CharField(default='user', max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='start_before_end'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.product')),
                ('engine', models.TextField(max_length=300)),
                ('platform', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('android', 'Android'), ('pc', 'PC'), ('ios', 'IOS')], max_length=7), default=list, size=None)),
            ],
            bases=('analytics.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='token',
            name='Product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='analytics.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
