# Generated by Django 5.1.7 on 2025-03-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_client_kpidata_globalkpidaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='VHOST_name',
            field=models.CharField(max_length=300),
        ),
    ]
