# Generated by Django 5.1.7 on 2025-06-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_gameeventhourlycount_bussinessevent_errorevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_event', models.IntegerField()),
                ('custom_field1', models.TextField(max_length=64)),
                ('custom_field2', models.TextField(max_length=64)),
                ('custom_field3', models.TextField(max_length=64)),
                ('custom_field4', models.TextField(max_length=64)),
                ('custom_field5', models.TextField(max_length=64)),
            ],
        ),
    ]
