# Generated by Django 5.1.7 on 2025-03-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_token_vhost_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalkpidaily',
            options={'get_latest_by': 'date'},
        ),
        migrations.AddField(
            model_name='globalkpidaily',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globalkpidaily',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
