# Generated by Django 5.1.7 on 2025-04-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_product_remove_token_user_remove_token_vhost_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=300, unique=True),
        ),
    ]
