# Generated by Django 5.1.7 on 2025-04-08 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_globalkpidaily_options_globalkpidaily_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='kpidata',
            name='client',
        ),
        migrations.RemoveField(
            model_name='kpidata',
            name='token',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cid',
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SessionEndEvent',
            fields=[
                ('gameevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.gameevent')),
            ],
            bases=('analytics.gameevent',),
        ),
        migrations.CreateModel(
            name='SessionStartEvent',
            fields=[
                ('gameevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.gameevent')),
                ('platform', models.TextField(max_length=100)),
            ],
            bases=('analytics.gameevent',),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.client'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('platform', models.TextField(max_length=100)),
                ('duration', models.DurationField(editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.client')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.token')),
            ],
        ),
        migrations.AddField(
            model_name='gameevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.session'),
        ),
        migrations.DeleteModel(
            name='GlobalKPIDaily',
        ),
        migrations.DeleteModel(
            name='KPIData',
        ),
        migrations.AddConstraint(
            model_name='gameevent',
            constraint=models.UniqueConstraint(fields=('time', 'client', 'session'), name='unique_event'),
        ),
    ]
