# Generated by Django 5.1.7 on 2025-06-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_TopErrorTypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARPPU',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('arppu', models.FloatField()),
            ],
            options={
                'db_table': 'aRPPU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AverageFPS',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('average_FPS', models.FloatField()),
            ],
            options={
                'db_table': 'averageFPS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AverageMemoryUsage',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('average_memory_usage', models.FloatField()),
            ],
            options={
                'db_table': 'averageMemoryUsage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AverageSessionDuration',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('average_session_duration', models.FloatField()),
            ],
            options={
                'db_table': 'averageSessionDuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AverageTriesPerLevel',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('progression01', models.CharField(max_length=300)),
                ('avg_tries', models.FloatField()),
            ],
            options={
                'db_table': 'averageTriesPerLevel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrashRate',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('crash_rate', models.FloatField()),
            ],
            options={
                'db_table': 'crashRate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyActiveUsers',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('active_users', models.IntegerField()),
            ],
            options={
                'db_table': 'dailyActiveUsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameEventHourlyCount',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('event_count', models.IntegerField()),
            ],
            options={
                'db_table': 'gameeventcount_hourly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LevelCompletionRate',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('progression01', models.CharField(max_length=300)),
                ('completion_rate', models.FloatField()),
            ],
            options={
                'db_table': 'levelCompletionRate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NetResourceFlow',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('itemType', models.CharField(max_length=300)),
                ('net_flow', models.IntegerField()),
            ],
            options={
                'db_table': 'netResourceFlow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceSinkRatio',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('itemType', models.CharField(max_length=300)),
                ('sink_ratio', models.FloatField()),
            ],
            options={
                'db_table': 'resourceSinkRatio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopErrorTypes',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('occurrences', models.IntegerField()),
            ],
            options={
                'db_table': 'topErrorTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotalRevenuePerCurrency',
            fields=[
                ('bucket', models.DateTimeField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=300)),
                ('total_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'totalRevenuePerCurrency',
                'managed': False,
            },
        ),
    ]
